
FROM node:iron-alpine

ENV npm_config_yes=true
ENV npm_config_engine_strict=false

WORKDIR /usr/src/app

COPY ["package*.json",  "./"]

RUN npm ci && npm cache clean --force && rm -rf /tmp/* /var/cache/apk/*

COPY . .

RUN npm run build

EXPOSE 4000

CMD ["sh", "-c", "npm run migration:run && npm run start:debug"]